### ISSUE TITLE
[QUESTION] How do I hide a custom playlist?

### ISSUE THREAD

**Issue by mikedumka** [pnp/custom-learning-office-365#256]
Hello, after the last update I can no longer hide (or un-hide) custom playlists. 

I have a playlist I want show in recommended (create impactful content together) and I cannot get it to show.  

Thanks
![mlp-screen](https://user-images.githubusercontent.com/4265230/81572362-bde4ed00-9368-11ea-9a39-70045104f389.png)

**Comment by juliemturner** [comment]
We've seen this a few times, and I can never get someone to work with me long enough to fix it.  The quick fix that others have found is to set a technology and save the playlist, and then refresh your client view and it should show up.  After you do this you should then be able to set it back to blank.

**Comment by juliemturner** [comment]
If you want to work with me more on it instead if you could send me the contents of the JSONData field for the playlist in question (in the CustomPlaylists list) that might help me understand what's going on.

**Comment by mdumka** [comment]
Hi Julie ... sorry for the delay ... had to put another fire with a migration project 🙂

How can I get that custom JSON data for you?

**Comment by juliemturner** [comment]
Look in the CustomPlaylists list, find the playlist item for the playlist in question and copy the contents of the JSONData field and paste it in a response.

**Comment by mdumka** [comment]
Hi @juliemturner I am SOOOOOO sorry for the delay in getting back to you on this. Here is what I have ... 

`{"Id":"12","Title":"Introduction to Learning Pathways","Image":"https://pnp.github.io/custom-learning-office-365/learningpathways/v3/images/playlists/playlist_bw.png","LevelId":"","AudienceId":"","TechnologyId":"","SubjectId":"","Source":"Tenant","CatId":"efa40872-92c7-4c1e-895c-7368c8d8f802","Description":"Learn the basics of navigating learning pathways.","StatusTagId":"","StatusNote":"","Assets":["6"]}`

**Comment by juliemturner** [comment]
It's been so long I almost forget what we're doing... since I have you now, can you give me the same JSONData payload for one that is showing up...

**Comment by juliemturner** [comment]
Although that said, I actually think I see the issue... that CatID doesn't actually exist (should be the GUID of a category/subcategory in the metadata.json -- for v3). It'll be really interesting to see the payload of one of the playlists that do show up.

**Comment by juliemturner** [comment]
Also, can you let me know the version of the solution you're running (the sppkg version in your app catalog)

**Comment by juliemturner** [comment]
Ok... well I figured it out and ironically the issue was solved in v4.  Basically what happened is that the Recommended category id was changed in the update and so all your playlists had incorrect CatId's... when you edit the playlist and save it it fixes the CatId so that's why the playlists shows up again.  In V4 this was fixed by placing all playlists that have a missing CatID in an "abandoned" section at the top of the admin screen so that they could be adjusted accordingly.  So, your fix is to edit the playlists and make sure the Category is selected and save it... going forward is the UI will help you along in this fix.  Thanks so much for helping me track it down!

**Comment by mdumka** [comment]
Hi @juliemturner I tried to do the fixes you mentioned. 

I updated to the latest version and edited and saved the playlist but still can't seem to hide it. Do you need me to add the JSON back in here? I added a new playlist after I updated and I can't hide that either ...

**Comment by juliemturner** [comment]
So you're now on v4.0.2?  If so, you ran the upgrade?

**Comment by mdumka** [comment]
@juliemturner Yup. Running 4.0.2.0

**Comment by juliemturner** [comment]
So wait... I got confused.. I thought you were saying you couldn't hide/show Microsoft's playlists... I misread your original post.  We've never had a feature that allows you to hide/show custom playlists... it's an open enhancement request but not one we've addressed to date.

**Comment by mdumka** [comment]
Ok, so just so I can confirm ... going all the way up to the top ... if I create a custom playlist, the only way to "hide" it is to delete it?

Again, thanks for all of the help, I really do appreciate it and hope that I am not being a pain!

**Comment by juliemturner** [comment]
Yes, that's correct.  Sorry, since we never had a feature to hide custom playlists, I just read it as couldn't hide a Microsoft playlist.  Sorry about the confusion.

**Comment by mdumka** [comment]
No problem ... thanks for all of your help! Stay safe!
