### ISSUE TITLE
 Unable to add new subcategories to 'Get Started' or 'Scenarios' sections. 

### ISSUE THREAD

**Issue by KRReilly** [pnp/custom-learning-office-365#623]
## 
When trying to add a new subcategory to the 'Get Started' or 'Scenarios' categories, the new sub-category does not save 

### To Reproduce

Go to Custom Learning Admin page > select 'Get Started' or 'Scenarios' section > add new heading under 'Subcategory Heading - English - United States' > select 'save'  

After 
### Expected behavior

After going through this process in 'Get Started' or 'Scenarios' categories, I would expect the new subcategory to be added after the change saves. However, I am able to add subcategories following this same process to 'Products' and 'Adoption Tools' categories.

### Learning Pathways version number

>4.3.0

### Additional context

>I was able to add subcategories in both of these sections in our test environment running the same version of Learning Pathways.

**Comment by amitkh22** [comment]
Hi @KRReilly, Thank you for reporting this. We will need some more information to help you with this as I tried to reproduce this issue but was able to add a subcategory successfully for both the mentioned categories.
Do you see any error on the screen or in the browser console when you click on "Save"? If yes, please share the screenshot of that error.

**Comment by KRReilly** [comment]
Thank you for a quick response: here is a recording of what is happening there is no error
https://user-images.githubusercontent.com/93666495/150214885-01673043-b296-4e7b-b9df-de8e050f042e.mov

**Comment by amitkh22** [comment]
Hi @KRReilly, thank you for providing the screen recording for the issue. Can you please also share a screenshot from the browser console for any error?
Here how you can get it --> Go the Custom Learning Admin page > click F12(or **fn + F12** depending on your keyboard setting), this will open the developer tools > navigate to **Console** tab > now try to add subcategory in "Get Started" or "Scenarios" section and save > if any error logs into Console on Save button click, please share that error.

**Comment by KRReilly** [comment]
Yes, here is the error:
![Screen Shot 2022-01-20 at 8 28 08 AM](https://user-images.githubusercontent.com/93666495/150357665-8a500ce3-f3f4-44c7-b1c5-caae98a43b89.png)
 
We found that by updating our test site to 4.3.0 - we received this error - however when we updated to 4.3.1 the error did not occur.

**Comment by amitkh22** [comment]
Hi @KRReilly, unfortunately there is not much information we can get from this error. Are you using any custom content pack?
This issue seems to be similar to this one #334 reported earlier. You can try the solution mentioned in that. You'll need to navigate to site contents > Custom Config list and delete everything from it. After that navigate to the CustomLearningAdmin.aspx  and try to add the subcategory. 
Let me know if that helps.

**Comment by dcashpeterson** [comment]
@KRReilly When we have seen this in the past it is generally an issue with the cache. If updating fixed the issue then I would suggest updating to V4.3.1 and as @amitkh22 said, clearing out the cache and having it rebuild should resolve that issue.

**Comment by KRReilly** [comment]
@dcashpeterson @amitkh22 after updating to V4.3.1, the issue is still occurring. I have also tried deleting everything in CustomConfig twice and am still unable to add a subcategory. When I try to add the subcategory: these errors occur when I select 'Add new Subcategory +': 
<img width="578" alt="Screen Shot 2022-01-26 at 4 52 22 PM" src="https://user-images.githubusercontent.com/93666495/151253484-96302e8e-9650-4c05-a24e-6f8d03e59830.png">
<img width="602" alt="Screen Shot 2022-01-26 at 4 52 29 PM" src="https://user-images.githubusercontent.com/93666495/151253492-4efb01d6-d7b9-4ea3-b5ee-f3ef212c2e4c.png">

When I select save the new subcategory, nothing happens and this error occurs: 
<img width="577" alt="Screen Shot 2022-01-26 at 4 55 31 PM" src="https://user-images.githubusercontent.com/93666495/151253595-c00eb20c-dc08-4f8e-94fc-11bb2350ae10.png">

**Comment by dcashpeterson** [comment]
@KRReilly I need to think about this one. I can't reproduce it on our end so I need the figure our a way to repro it so I can see if it is a data issue or a bug in the code.

**Comment by KRReilly** [comment]
@dcashpeterson I appreciate your reviewing this thank you. We are in a bit of a crunch on our end to publish our site with Learning Pathways - do you have an idea of timing on when you may have the bandwidth to review this issue?

**Comment by dcashpeterson** [comment]
@KRReilly I looked at this again and I still can't reproduce this. Has anything changed? As we mentioned before when we have seen this before it turns out the be an issue with either the cache or an issue with data. Do you have any custom subcategories at all? Did you deploy 4.3.X directly or did you upgrade?

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please open a new issue.
