### ISSUE TITLE
 Dropdown selection of playlist item is not working in V5

### ISSUE THREAD

**Issue by adriangoszczynski** [pnp/custom-learning-office-365#850]
## Describe the bug

Nothing happens if I change playlist using dropdown menu in the webpart. In the Developer Tools webpart following error appears:
M365LP:CustomLearning (_selectAsset) - TypeError: Cannot read properties of undefined (reading 'Id')

### To Reproduce

Update Learning Pathways to V5 and try to change playlist item with dropdown menu.

### Expected behavior

Once another item is selected, webpart should switch to it.

### Learning Pathways version number

5.0.0.4

### Additional context

Previous and Next buttons works as expected.

**Comment by dcashpeterson** [comment]
@adriangoszczynski thanks for reporting this. Can you please provide more details? I tested this with the out of the box playlists and using the drop down worked fine. Is there a specific playlist you found that it wasn't working in?

**Comment by adriangoszczynski** [comment]
@dcashpeterson additionally, I just found that if you choose to setup webpart with specific playlist, you can see only one playlist per subcategory

![image](https://github.com/user-attachments/assets/fa1d46f8-dc33-4e81-92c2-14012102208f)

**Comment by Emac725** [comment]
I have the same issue, however with the update I can't even open the ///sites/M365LP/SitePages/CustomLearningAdmin.aspx, 
I get a File not found 404 error and we can't seem to roll the update back.

**Comment by AndyHuneycutt-AH** [comment]
Hi @dcashpeterson I can add to the issue. The **Select a filter** > **Playlist** | **Filter to Playlist** only returns the first item from the subcategory. Including a screenshot: 

On the left you can see I have two playlists under the subcategory. On the right only the first playlist is showing: 
![Screenshot 2024-10-15 at 5 00 34 PM](https://github.com/user-attachments/assets/0aaaa11f-b7a3-4eea-9fc7-a0d453f8bea6)

**Comment by dcashpeterson** [comment]
Thanks folks. I'll look at this and report back when I have something to report.

**Comment by Emac725** [comment]
My issue is related but slightly different.
For Custom Playlists, before the update, I could select a category from the drop-down menu which would auto display below. Now I must use the Next or Back buttons to advance to each category within the playlist.
![dropdown in Training site](https://github.com/user-attachments/assets/90c0b9c9-d720-47f7-9f67-9a8ca1bc3a7b)

**Comment by dcashpeterson** [comment]
@adriangoszczynski This issue is in progress.

**Comment by droogsdontrun** [comment]
Is the issue that Emac725 raised sorted out yet?  I'm seeing the same behaviour.

**Comment by dcashpeterson** [comment]
This is in progress. I am working on fixing both bugs.

**Comment by StuatElliottAdams** [comment]
I don't suppose we have a rough fix date on this issue do we?

**Comment by dcashpeterson** [comment]
@StuatElliottAdams, @droogsdontrun, @Emac725 I apologize for the delay. This is a community project so we work on this in our free time. Unfortunately, I have not had a chance to make the fix. If you are a developer and want to take a stab at fixing it I am happy to accept a PR. I will update the issue when I have a fix ready for release. Again, I apologize for the delay.

**Comment by dcashpeterson** [comment]
All these issues have been addressed in v. 5.0.0.6

**Comment by HamEv** [comment]
@dcashpeterson I recently have updatete to v. 5.0.0.6 

![Image](https://github.com/user-attachments/assets/722eef9f-30ee-4d7d-af5c-d90f276af0c6)

but I'm still not able to to select an item via dropdownlist for a custom playlist:

![Image](https://github.com/user-attachments/assets/f6dbcb80-a5d1-412e-9fcd-ebb763f85a88)

Is there anything I've missed? Thanks.

**Comment by Heavm00** [comment]
@dcashpeterson 
Do you have an idea, why this is still not working in my environment? The error show is:
M365LP:CustomLearning (_selectAsset) - TypeError: Cannot read properties of undefined (reading 'Id')

v. 5.0.0.6 is used.

**Comment by dcashpeterson** [comment]
@Heavm00 This issue is closed as we rolled out the fix for it with V 5.0.0.6. This fix has been tested both in English and in other languages and has been resolved. You can try to delete the cache in the admin site and have it regenerate with new IDs. That should help.

**Comment by Heavm00** [comment]
@dcashpeterson  thanks for your answer. Can you please tell me how to delete the catche and regenerate the new IDs? Is there any guideline for doing that?

**Comment by dcashpeterson** [comment]
@Heavm00  you delete the cache by going to the admin site and the CustomConfig list. Delete everything in the list with the title of CustomConfig. Then reload the admin web part screen and the cache will reset in the background.

**Comment by Heavm00** [comment]
@dcashpeterson thank for that information. I deleted all of the items in CustomConfig list. Cache was resetet and new items have been created. Unfortunatly nothing has changed - I cannot select the items.

**Comment by dcashpeterson** [comment]
@Heavm00  This was the error that was being seen before the fix was rolled out. I can't reproduce it so I will need some additional information.

Can you please confirm that this is a custom sub-category created under products? Is this a custom playlist under a custom sub-category? Are all the assets custom or are some Learning Pathways assets? Are you using a custom content pack?

Are you encountering the error in the same site collection as the learning pathways admin web part or in a site other than the Learning Pathways site.

**Comment by Heavm00** [comment]
@dcashpeterson 

I have created several sub-categories under Products with custom playlists. I don't use any Learning Pathways assets in these areas. I don't use a custom content pack - everything has been created directly within Learning Pathways. Here you can see my custom Planner sub-category: 

![Image](https://github.com/user-attachments/assets/b102c4f3-5eac-44c8-bf5d-3849095be224)

My playlists reference content from Microsoft (blue arrows) or content I created and stored in the Pages library (red arrows). I have also used custom aspx files with Microsoft content embedded with a WebPart.

![Image](https://github.com/user-attachments/assets/186d404c-3c4c-4591-8439-5c715542e263)

I have only one site collection that contains the Admin Web Part and learning path content.

The following errors occur when you try to click in the drop-down list (red arrow):

![Image](https://github.com/user-attachments/assets/65a00e43-4d74-4ce8-9725-8448d811d9b9)

Is there another location where old JS data from the previous version is stored? My current version is the latest and the app is updated too:

![Image](https://github.com/user-attachments/assets/5e27be27-1988-4574-974f-c71abcf66232)

**Comment by dcashpeterson** [comment]
@Heavm00  I will try to replicate this with this information. In the mean time, try this. The solution isn't using tenant wide deployment so check the site collection that you have it installed in. Go to Site Contents > Microsoft 365 Learning Pathways > Details and double check the version updated in the site collection. It should be automatic but maybe it didn't update.

**Comment by Heavm00** [comment]
I have updated that manually three weeks ago:

![Image](https://github.com/user-attachments/assets/894a6c3d-bdcc-43b7-80e3-9615ac444df7)

**Comment by dcashpeterson** [comment]
@Heavm00 I have tried to replicate this issue with the latest build and have been unable to do so. At this point the only thing I can think of would be to remove the solution from the app catalog and then add it again. This should have no impact on the Learning Pathways site and would only have downtime between when you remove and re-add the solution.
