### ISSUE TITLE
Unable to filter playlist on M365 learning pathways webpart

### ISSUE THREAD

**Issue by terriyaki0212** [pnp/custom-learning-office-365#898]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Not sure if it is a bug or if there's something I'm missing. The Learning Pathways site is working fine but we're unable to get to filter playlists from the M365 Learning Pathways webpart. We're not getting any options, it just says none. 

### To Reproduce

When we deploy the webpart to any site, we are unable to get the list of playlists to show for filtering. We do get options for Category and Sub-Category but not for Playlist.

### Expected behavior

Able to see the list of available playlists in the Filter dropdown

### Screenshots

![Image](https://github.com/user-attachments/assets/ea136eb7-8149-4dda-9604-ada4c489a8b8)

### Learning Pathways version number

We just recently performed the upgrade. The app is now in version 5.0.0.6

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@terriyaki0212 let me look into this.

**Comment by AlexLetics** [comment]
@dcashpeterson we have the same problem and we're using custom playlists extensively. Please keep us updated. Thank you so much.

**Comment by dcashpeterson** [comment]
@terriyaki0212 @AlexLetics This should have been resolved in a fix that rolled out months ago. The only thing I can think of is that I forgot to update the version. I just updated the schema to V.5.0.0.7. Try to update to that and see if it fixes the issue.

**Comment by AlexLetics** [comment]
> [@terriyaki0212](https://github.com/terriyaki0212) [@AlexLetics](https://github.com/AlexLetics) This should have been resolved in a fix that rolled out months ago. The only thing I can think of is that I forgot to update the version. I just updated the schema to V.5.0.0.7. Try to update to that and see if it fixes the issue.

Thank you very much for the quick response. We'll update and see. I saw that is was fixed a while ago. Strange behaviour. I'll keep you updated @dcashpeterson

**Comment by AndyHuneycutt-AH** [comment]
@dcashpeterson I updated to V.5.0.0.7. I'm still seeing the same issue reported here and in Issue #850. 

Attached are two screenshots. One image shows adding a new Learning Pathways web part, Select a Filter > Playlist, Filter to Playlist > only shows **none**. 
![Image](https://github.com/user-attachments/assets/c23e0428-9c9b-4b20-bc19-277d032f1e83)

Second image shows a previous Learning Pathways web part, Select a Filter > Playlist, Filter to Playlist > **none**, Select an Asset > default value prior to updating Learning Pathways. I cannot select a new playlist or asset from the dropdowns. 
![Image](https://github.com/user-attachments/assets/fa3e0619-875a-4579-ad11-91ec8d666f2f)

Please let me know if I can provide any logs or diagnostics. Thanks.

**Comment by AlexLetics** [comment]
> [@AndyHuneycutt-AH](https://github.com/AndyHuneycutt-AH) and [@terriyaki0212](https://github.com/terriyaki0212) have you cleared out the cache in the CustomConfig list? I am not able to replicate this issue any longer. This was an issue in the previous version but has been updated and resolved. Please clear out the customconfig cache and also if you are not using tenant wide deployment make sure that the app installed in the site collection is updated to the latest version.

Thank you @dcashpeterson! We'll try and let you know. In our case its a site collection deployment I think.

**Comment by AlexLetics** [comment]
> > [@AndyHuneycutt-AH](https://github.com/AndyHuneycutt-AH) and [@terriyaki0212](https://github.com/terriyaki0212) have you cleared out the cache in the CustomConfig list? I am not able to replicate this issue any longer. This was an issue in the previous version but has been updated and resolved. Please clear out the customconfig cache and also if you are not using tenant wide deployment make sure that the app installed in the site collection is updated to the latest version.
> 
> Thank you [@dcashpeterson](https://github.com/dcashpeterson)! We'll try and let you know. In our case its a site collection deployment I think.

@dcashpeterson we checked the deployment method. Its tenant wide. I cleared the cache using browser developer tools. Is that what you meant by clear the customconfig cache?

**Comment by dcashpeterson** [comment]
@AlexLetics Learning Pathways creates it's own cache of all the available assets so we are not running a query every time the webpart is loaded. To do this go to the admin site > Site Contents > CustomConfig list. Filter to items with the title CustomConfig. Delete those items. The next time the webpart is loaded it will recreate the cache.

**Comment by AlexLetics** [comment]
> [@AlexLetics](https://github.com/AlexLetics) Learning Pathways creates it's own cache of all the available assets so we are not running a query every time the webpart is loaded. To do this go to the admin site > Site Contents > CustomConfig list. Filter to items with the title CustomConfig. Delete those items. The next time the webpart is loaded it will recreate the cache.

Hi @dcashpeterson still no luck 🙁. I deleted the config files and they were recreated, but the playlists still don't show!

**Comment by dcashpeterson** [comment]
@terriyaki0212 and @AndyHuneycutt-AH  I have a beta build for you to test and see if it fixes the issue. If you are willing to test it It would be appreciated. https://github.com/pnp/custom-learning-office-365/tree/main/installation/Beta/V5.0.0.8

If it doesn't work you should be able to install this over it. https://github.com/pnp/custom-learning-office-365/blob/main/installation/customlearning.sppkg

**Comment by dcashpeterson** [comment]
@terriyaki0212 @AlexLetics @ChrisGray-97 This was resolved in V5.0.0.9. Please upgrade the solution for the issue. We did see some issues where there were errors in custom created items such as sub-categories or custom assets. If that is the case you will need to delete and recreate those assets in the UI for M365 learning pathways.
